"""
This module contains a set of servers that are filtered out from the
Google News feed due to low quality content or requiring a subscription.
"""

FILTERED_SOURCES = {
    "Bloomberg",
    "Business Insider",
    "Forbes",
    "Haaretz",
    "The New York Times",
    "The Wall Street Journal",
    "The Washington Post",
}

KNOWN_GOOD_SOURCES = {
    "ABC 10 News San Diego KGTV",
    "ABC News",
    "ABC7 Los Angeles",
    "Al Jazeera English",
    "Ars Technica",
    "Axios",
    "BBC.com",
    "Benzinga",
    "Big Think",
    "Bitcoinist",
    "BleepingComputer",
    "BuzzFeed",
    "CBS News",
    "CNBC",
    "CNET",
    "CNN",
    "Daily Kos",
    "Daily Mail",
    "Earth.com",
    "Engadget",
    "European Space Agency",
    "Financial Times",
    "Fortune",
    "Fox Business",
    "Fox News",
    "GB News",
    "GQ",
    "Gizmodo",
    "Health.com",
    "HuffPost",
    "IGN",
    "Interesting Engineering",
    "Investor's Business Daily",
    "KETV Omaha",
    "KHON2",
    "KIDO Talk Radio",
    "KSL.com",
    "Kyiv Independent",
    "Live and Let's Fly",
    "Los Angeles Times",
    "Medical News Today",
    "NBC News",
    "NDTV",
    "NPR",
    "Neuroscience News",
    "New York Post",
    "Newser",
    "Newsweek",
    "Noozhawk",
    "POLITICO Europe",
    "POLITICO",
    "Phys.org",
    "PsyPost",
    "Reuters",
    "SciTechDaily",
    "ScienceAlert",
    "Simple Flying",
    "Slate",
    "South China Morning Post",
    "Space.com",
    "SpaceNews",
    "Spaceflight Now",
    "TESLARATI",
    "TODAY",
    "The Advocate",
    "The Arizona Republic",
    "The Associated Press",
    "The Conversation",
    "The Daily Beast",
    "The Daily Galaxy --Great Discoveries Channel",
    "The Guardian US",
    "The Hacker News",
    "The Motley Fool",
    "The Seattle Times",
    "The Times of India",
    "The Times of Israel",
    "The Verge",
    "TipRanks",
    "USA TODAY",
    "WTOP",
    "Women's Health",
    "Yahoo Finance",
    "Yahoo Life",
    "mySA",
    "TechCrunch",
    "Gothamist",
}
