name: lint

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 12
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.13"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Create virtual environment and install dependencies
        run: |
          which python
          python --version
          id; sudo id
          sudo apt install -y cloc libgirepository1.0-dev
          time make install
          source .venv/bin/activate && env PYTHONPATH=src:. ruff check
          source .venv/bin/activate && env PYTHONPATH=src:. echo pyright .
          source .venv/bin/activate && env PYTHONPATH=src:. mypy --strict --warn-unreachable --ignore-missing-imports --no-namespace-packages .
          source .venv/bin/activate && env PYTHONPATH=src:. python -m unittest -v tests/[girw]*_test.py
